accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from .views import RegistrationFormView, CustomPasswordChangeView, profile_view, profile_detail

app_name = "accounts"

urlpatterns = [
    path('', profile_view, name='profile_info'),
    path('detail/<int:user_id>/', profile_detail, name='profile_detail'),

    path('auth/login/',
         auth_views.LoginView.as_view(template_name='registration/login.html', redirect_authenticated_user=True),
         name='login'),
    path('auth/logout/', auth_views.LogoutView.as_view(template_name='registration/login.html', next_page='/'),
         name='logout'),
    path('auth/registration/', RegistrationFormView.as_view(template_name='registration/registration.html',
                                                            success_url=reverse_lazy('accounts:login')),
         name='register'),
    path('auth/password_change/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),
    path('auth/password_change/', CustomPasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done'),
                                                              template_name='registration/password_change.html'),
         name='password_change'),
    path('auth/password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('auth/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_change_done')),
         name='password_reset_confirm'),
    path('auth/password_reset/',
         auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
         name='password_reset'),
]

orders/urls.py
from django.urls import path
from .views import SpecialistsListView, order_view, spec_view, my_orders

app_name = "orders"

urlpatterns = [
    path('list-specialists/', SpecialistsListView.as_view(), name='list_specialists'),
    path('order/<int:category_id>/', order_view, name='order_work'),
    path('select-spec/', spec_view, name='select_order'),
    path('my-orders/', my_orders, name='my_order'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import MainPageView

urlpatterns = [
    path('', MainPageView.as_view(), name='base_page'),
    path('admin/', admin.site.urls),
    path('profile/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/views.py
from django.views.generic import TemplateView


class MainPageView(TemplateView):
    template_name = "index.html"

project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta content="" name="descriptison">
    <meta content="" name="keywords">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i"
          rel="stylesheet">

    {% block CssFile %}
    <!-- Different support CSS Files -->
    <link href="{% static 'different/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'different/icofont/icofont.min.css' %}" rel="stylesheet">
    <link href="{% static 'different/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'different/venobox/venobox.css' %}" rel="stylesheet">
    <link href="{% static 'different/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'different/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">


    <!-- Template Main CSS File -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    {% endblock %}

    <title>{% block title %}FixPC.ru{% endblock %}</title>
</head>
<body>
{% block header %}
<!-- ======= Header ======= -->
<header id="header" class="fixed-top">
    <div class="container-fluid d-flex">
        <div class="logo mr-auto">
            <h1 class="text-light"><a href="/"><span>FixPC.ru</span></a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
        </div>

        <!-- Start nav-menu -->
        <nav class="nav-menu d-none d-lg-block">
            <ul>
                <li class="active"><a href="{% url 'base_page' %}#hero">Главная</a></li>
                <li><a href="{% url 'base_page' %}#about">О нас</a></li>
                <li><a href="{% url 'base_page' %}#services">Сервис</a></li>
                <li><a href="{% url 'orders:select_order' %}">Заказать работу</a></li>
                <li><a href="{% url 'orders:list_specialists' %}">Специалисты</a></li>
                {% if request.user.is_authenticated %}
                <li>
                    <ul>
                        <li class="drop-down">
                            <a href="#">
                                <img class="img-circle img-fluid img-thumbnail" width="25px" height="25px" src="{{ request.user.profile.get_avatar }}">
                                {{ request.user.username }}
                            </a>
                            <ul>
                                <li><a href="{% url 'accounts:profile_info' %}">Профиль</a></li>
                                <li><a href="{% url 'orders:my_order' %}">Мои заказы</a></li>
                                <li><a href="{% url 'accounts:logout'%}?next=/">Выход</a></li>
                            </ul>
                        </li>

                    </ul>
                </li>
                {% else %}
                <li class="get-started">
                    <a href="{% url 'accounts:login'%}">Войти</a>
                </li>
                {% endif %}

            </ul>
        </nav>
        <!-- End nav-menu -->
    </div>
</header>
<!-- End Header -->
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
<!-- ======= Footer ======= -->
<footer id="footer" class="fixed-bottom">
    <div class="container py-4">
        <div class="copyright">
            &copy; Copyright <strong><span>FixPC.ru</span></strong>. Все права защищены.
        </div>
    </div>
</footer>
<!-- End Footer -->
{% endblock %}

{% block JSFile %}
<!-- Support JS Files -->
<script src="{% static 'different/jquery/jquery.min.js' %}"></script>
<script src="{% static 'different/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'different/jquery.easing/jquery.easing.min.js' %}"></script>


<!--<script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>-->
<script src="{% static 'different//venobox/venobox.min.js' %}"></script>
<script src="{% static 'different/owl.carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'different/aos/aos.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'js/main.js' %}"></script>
{% endblock %}
</body>
</html>

project/templates/index.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<!-- ======= Short info Section ======= -->
<div class="mt-section d-block">
    <section id="hero" class="d-flex align-items-center ">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 pt-5 pt-lg-0 order-2 order-lg-1">
                    <h1>FixPC.ru лучший севис по ремонту ПК.</h1>
                    <h2>Быстрое, качественное выполнение любых видов работ в кратчайшие сроки.</h2>
                    <a href="{% url 'base_page' %}#portfolio" class="btn-get-started scrollto">Сделать заказ</a>
                </div>
                <div class="d-none d-sm-none d-md-block col-lg-6 order-1 order-lg-2 hero-img">
                    <img src="{% static 'img/repairman.png' %}" class="img-fluid animated" alt="">
                </div>
            </div>
        </div>

    </section>
    <!-- End Short info Section -->

    <main id="main">
        <!-- ======= About Section ======= -->
        <section id="about" class="about">
            <div class="container">

                <div class="row justify-content-between">
                    <div class="col-lg-5 d-flex align-items-center justify-content-center about-img">
                        <img src="{% static 'img/pc.jpg' %}" class="img-fluid" alt="" data-aos="zoom-in">
                    </div>
                    <div class="col-lg-6 pt-5 pt-lg-0">
                        <h3 data-aos="fade-up">Кто мы?</h3>
                        <p data-aos="fade-up" data-aos-delay="100">
                            Мы молодая, инициативная команда проффессионалов по ремонту персональных копьютеров,
                            а также разработке, установке и наладке программного обеспечения.
                        </p>
                        <div class="row">
                            <div class="col-md-6" data-aos="fade-up" data-aos-delay="100">
                                <i class="bx bx-receipt"></i>
                                <h4>Разработка ПО</h4>
                                <p>Разработка ПО любой сложности в кратчайшие сроки.</p>
                            </div>
                            <div class="col-md-6" data-aos="fade-up" data-aos-delay="200">
                                <i class="bx bx-cube-alt"></i>
                                <h4>Ремонт</h4>
                                <p>Ремонт, чистка, установка ПО на любые ПК по доступным ценам.</p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </section><!-- End About Section -->

        <!-- ======= Services Section ======= -->
        <section id="services" class="services section-bg">
            <div class="container">

                <div class="section-title" data-aos="fade-up">
                    <h2>Сервис</h2>
                    <p>Наши предложения</p>
                </div>

                <div class="row">
                    <div class="col-md-6 col-lg-3 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
                        <div class="icon-box">
                            <div class="icon"><i class="bx bxl-dribbble"></i></div>
                            <h4 class="title"><a href="">Служба поддержки</a></h4>
                            <p class="description">Круглосуточная служба поддержки для консультации по любому виду
                                работ.</p>
                        </div>
                    </div>

                    <div class="col-md-6 col-lg-3 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-box">
                            <div class="icon"><i class="bx bx-file"></i></div>
                            <h4 class="title"><a href="">Лучшие цены</a></h4>
                            <p class="description">Низкие цены на все виды работ</p>
                        </div>
                    </div>

                    <div class="col-md-6 col-lg-3 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="300">
                        <div class="icon-box">
                            <div class="icon"><i class="bx bx-tachometer"></i></div>
                            <h4 class="title"><a href="">Скорость работы</a></h4>
                            <p class="description">Выполнение любых видов работ в кратчайшие сроки.</p>
                        </div>
                    </div>

                    <div class="col-md-6 col-lg-3 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="400">
                        <div class="icon-box">
                            <div class="icon"><i class="bx bx-world"></i></div>
                            <h4 class="title"><a href="">Выезд мастера</a></h4>
                            <p class="description">Выезд мастера на дом для диагности и ремонта.</p>
                        </div>
                    </div>

                </div>

            </div>
        </section><!-- End Services Section -->

        <!-- ======= Portfolio Section ======= -->
        <section id="portfolio" class="portfolio">
            <div class="container">

                <div class="section-title" data-aos="fade-up">
                    <h2>Предложения</h2>
                    <p>Виды работ</p>
                </div>

                <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="200">

                    <div class="col-lg-6 col-md-6 portfolio-item filter-app">
                        <div class="portfolio-wrap">
                            <img src="{% static 'img/development.jpg'%}" class="img-fluid" alt="">
                            <div class="portfolio-links">
                                <a href="{% url 'orders:order_work' category_id=1%}" class="text-center btn-orange"
                                   title="App 1">Заказать</a>
                            </div>
                            <div class="portfolio-info">
                                <h4>Разработка ПО</h4>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6 col-md-6 portfolio-item filter-web">
                        <div class="portfolio-wrap">
                            <img src="{% static 'img/fix_pc.png' %}" class="img-fluid text-center" alt="">
                            <div class="portfolio-links">
                                <a href="{% url 'orders:order_work' category_id=2%}" class="text-center btn-orange" title="Web 3">Заказать</a>

                            </div>
                            <div class="portfolio-info">
                                <h4>Ремонт ПК</h4>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </section>
        <!-- End Portfolio Section -->

        <!-- ======= Sample Work Section ======= -->
        <section id="clients" class="clients section-bg">
            <div class="container">

                <div class="section-title" data-aos="fade-up">
                    <h2>Работы</h2>
                    <p>Примеры выполненных работ</p>
                </div>

                <div class="owl-carousel clients-carousel" data-aos="fade-up" data-aos-delay="100">
                    <img class="img-fluid text-center " src="{% static 'img/sample_pc_1.jpg' %}" height="250px" alt="">
                    <img class="img-fluid text-center " src="{% static 'img/sample_pc_2.jpg' %}" height="250px" alt="">
                    <img class="img-fluid text-center " src="{% static 'img/sample_pc_3.jpg' %}" height="250px" alt="">
                    <img class="img-fluid text-center " src="{% static 'img/sample_pc_4.jpg' %}" height="250px" alt="">
                    <img class="img-fluid text-center " src="{% static 'img/sample_pc_5.jpg' %}" height="250px" alt="">
                </div>

            </div>
        </section>
        <!-- End Sample Work Section -->
    </main>
</div>
{% endblock %}

{% block footer %}
<!-- ======= Footer ======= -->
<footer id="footer" class="bg-white">
    <div class="container py-4">
        <div class="copyright">
            &copy; Copyright <strong><span>FixPC.ru</span></strong>. Все права защищены.
        </div>
    </div>
</footer>
<!-- End Footer -->
{% endblock %}