accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from .views import RegistrationFormView, CustomPasswordChangeView, profile_view, profile_detail

app_name = "accounts"

urlpatterns = [
    path('', profile_view, name='profile_info'),
    path('detail/<int:user_id>/', profile_detail, name='profile_detail'),

    path('auth/login/',
         auth_views.LoginView.as_view(template_name='registration/login.html', redirect_authenticated_user=True),
         name='login'),
    path('auth/logout/', auth_views.LogoutView.as_view(template_name='registration/login.html', next_page='/'),
         name='logout'),
    path('auth/registration/', RegistrationFormView.as_view(template_name='registration/registration.html',
                                                            success_url=reverse_lazy('accounts:login')),
         name='register'),
    path('auth/password_change/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),
    path('auth/password_change/', CustomPasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done'),
                                                              template_name='registration/password_change.html'),
         name='password_change'),
    path('auth/password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('auth/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_change_done')),
         name='password_reset_confirm'),
    path('auth/password_reset/',
         auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
         name='password_reset'),
]

orders/urls.py
from django.urls import path
from .views import SpecialistsListView, order_view, spec_view, my_orders

app_name = "orders"

urlpatterns = [
    path('list-specialists/', SpecialistsListView.as_view(), name='list_specialists'),
    path('order/<int:category_id>/', order_view, name='order_work'),
    path('select-spec/', spec_view, name='select_order'),
    path('my-orders/', my_orders, name='my_order'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import MainPageView

urlpatterns = [
    path('', MainPageView.as_view(), name='base_page'),
    path('admin/', admin.site.urls),
    path('profile/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from django.utils import timezone

from accounts.models import Specialization, TypeWork, UserAccount


class Order(models.Model):
    client = models.ForeignKey(UserAccount, on_delete=models.CASCADE, related_name='client', verbose_name='Заказчик')
    master = models.ForeignKey(UserAccount, on_delete=models.CASCADE, related_name='master', verbose_name='Исполнитель')
    spec_order = models.ForeignKey(Specialization, on_delete=models.CASCADE, verbose_name='Специализация заказа')
    type_work = models.ForeignKey(TypeWork, on_delete=models.CASCADE, verbose_name='Тип работы')
    date_of_completion = models.DateField(default=timezone.now, verbose_name="Дата выполнения работы", null=True)
    price = models.IntegerField(default=0, verbose_name='Стоимость работы')

    def __str__(self):
        return 'исполнитель: {}; тип работы: {}'.format(self.master, self.type_work)

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

orders/forms.py
from django import forms
from django.forms import ModelForm

from orders.models import Order


class FormOrderWork(ModelForm):
    client = forms.CharField(max_length=100, required=False, widget=forms.HiddenInput, label="Клиент:")
    master = forms.CharField(max_length=100, required=False, widget=forms.HiddenInput, label="Исполнитель:")
    spec_order = forms.CharField(max_length=100, label="Специализация:")
    type_work = forms.CharField(max_length=100, label="Тип работы:")
    date_of_completion = forms.DateField(
        widget=forms.DateInput(format=('%d-%m-%Y')), label="Дата выполнения работ:")
    price = forms.IntegerField(min_value=0, widget=forms.IntegerField, label="Стоимость работы:")

    # Стилизация формы
    def __init__(self, *args, **kwargs):
        super(FormOrderWork, self).__init__(*args, **kwargs)

        for item in self.fields:
            self.fields[item].widget = forms.TextInput(attrs={'class': 'form-control'})

    class Meta:
        model = Order
        fields = '__all__'

orders/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseNotFound, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView

from accounts.models import UserAccount, TypeWork, Specialization, Profile, Comment
from .forms import FormOrderWork
from .models import Order


def spec_view(request):
    return render(request, 'order_spec.html')


@login_required(login_url='accounts:login')
def my_orders(request):
    orders = Order.objects.filter(client=request.user)
    orders_to_do = Order.objects.filter(master=request.user)
    context = {
        'orders': orders,
        'orders_to_do': orders_to_do,
    }
    return render(request, 'my_order.html', context=context)


@login_required(login_url='accounts:login')
def order_view(request, category_id):
    users = UserAccount.objects.all()
    form = FormOrderWork()
    specialization = get_object_or_404(Specialization, id=category_id)

    try:
        type_work = TypeWork.objects.filter(specialization_id=category_id)

        if category_id == 1:
            masters = UserAccount.objects.filter(Q(profile__specialization_id=category_id) | Q(profile__position='master'))
        elif category_id == 2:
            masters = UserAccount.objects.filter(Q(profile__specialization_id=category_id) | Q(profile__position='programmer'))
        else:
            masters = UserAccount.objects.filter(Q(profile__specialization_id=category_id))
        avg = {}
        for item in masters:
            val_avd = Comment.avd_assessment(item.id)
            avg[item.username] = 0 if val_avd is None else val_avd
    except TypeWork.DoesNotExist:
        return HttpResponseNotFound()
    except UserAccount.DoesNotExist:
        return HttpResponseNotFound()

    if request.method == 'POST':
        form = FormOrderWork(request.POST, instance=request.user)
        if form.is_valid():
            Order.objects.create(
                client_id=request.user.id,
                master_id=form.cleaned_data['master'],
                spec_order_id=form.cleaned_data['spec_order'],
                type_work_id=form.cleaned_data['type_work'],
                date_of_completion=form.cleaned_data['date_of_completion'],
                price=form.cleaned_data['price']
            )
            return redirect('orders:my_order')

    context = {
        'form': form,
        'spec_id': specialization,
        'list_specialist': users,
        'type_work': type_work,
        'masters': masters,
        'avd': avg
    }
    return render(request, 'order.html', context=context)


class SpecialistsListView(ListView):
    context_object_name = 'list_specialist'
    template_name = 'specialist.html'

    def get_context_data(self, **kwargs):
        context = super(SpecialistsListView, self).get_context_data(**kwargs)
        context['number_page'] = self.request.GET.get('page')
        return context

    def get_queryset(self):
        data = UserAccount.objects.all()
        paginator = Paginator(data, 15)
        page = self.request.GET.get('page')
        try:
            data = paginator.page(page)
        except PageNotAnInteger:
            data = paginator.page(1)
        except EmptyPage:
            data = paginator.page(paginator.num_pages)
        return data

orders/templates/my_order.html
{% extends 'base.html' %}

{% block content %}
<!-- ======= My Orders Section ======= -->
<section class="contact mt-section">
    <div id="auth" class="container">
        <div class="section-title" data-aos="fade-up">
            <h2>Заказы</h2>
            <p>Мои заказы</p>
            <div class="col-12 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="100">
                <div class="php-email-form">
                    <div class="panel-body">
                        <div class="comments">
                            <h5 class="font-weight-bold">Заказанные:</h5>
                            <ul class="media-list">
                                {% for item in orders %}
                                <li class="media mb-3">
                                    <div class="media-body">
                                        <div class="comments-panel">
                                            <div class="alert alert-info text-left">
                                                <div class="author">Исполнитель: {{ item.master.get_full_name }}</div>
                                                <div class="metadata">
                                                    <span class="date">{{ item.date_of_completion|date:'d.m.Y' }}</span>
                                                </div>
                                            </div>
                                            <div class="panel-body pl-3 pr-3">
                                                <div class="media-text text-justify">
                                                    <div>Тип работы: {{ item.type_work.name }}</div>
                                                    <div>Стоимость работы: {{ item.price }}</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="comments">
                            <h5 class="font-weight-bold">Выполняемые:</h5>
                            <ul class="media-list">
                                {% for item in orders_to_do %}
                                <li class="media mb-3">
                                    <div class="media-body">
                                        <div class="comments-panel">
                                            <div class="alert alert-info text-left">
                                                <div class="author">Клиент: {{ item.master.get_full_name }}</div>
                                                <div class="metadata">
                                                    <span class="date">{{ item.date_of_completion|date:'d.m.Y' }}</span>
                                                </div>
                                            </div>
                                            <div class="panel-body pl-3 pr-3">
                                                <div class="media-text text-justify">
                                                    <div>Тип работы: {{ item.type_work.name }}</div>
                                                    <div>Стоимость работы: {{ item.price }}</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>

                    </div>
                </div>
                </form>
            </div>
        </div>
</section>

<!-- End My Orders Section -->
{% endblock %}

orders/templates/order.html
{% extends 'base.html' %}


{% load orders_extras %}
{% block content %}
<!-- ======= Profile Section ======= -->
<section class="contact mt-section">
    <div id="auth" class="container">
        <div class="section-title" data-aos="fade-up">

            <h2>Заказ</h2>
            <p>Оформление заказа</p>
            <form action="{% url 'orders:order_work' category_id=spec_id.id%}" method="post" role="form" class="row">
                {% csrf_token %}
                <div class="col-12 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="100">
                    <div class="php-email-form">
                        <div class="d-flex justify-content-start mb-4">
                            <a class="btn-orange " href="{% url 'orders:select_order' %}">Назад</a>
                        </div>
                        <div class="form-row col-12">
                                <div class="form-group row col-md-12">
                                    Специализация заказа: {{ spec_id.name }}
                                </div>
                            </div>

                        <div class="panel-body col-12">
                            <div class="form-row">
                                <div class="form-group row col-md-12">
                                    <input type="hidden" name="spec_order" value="{{ spec_id.id }}"/>
                                    {{ form.type_work.label_tag }}
                                    <div class="w-100">
                                        <select name="type_work" class="form-control selectpicker" id="id_type_workk">
                                            <option value="">Выберите тип работы</option>
                                            {% for item in type_work %}
                                            <option value="{{item.id}}">{{ item }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    {{ form.type_work.errors }}
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group row col-md-12">
                                    {{ form.master.label_tag }}
                                    <div class="w-100">
                                        <select name="master" class="form-control selectpicker" id="id_master">
                                            <option value="">Выберите исполнителя</option>
                                            {% for item in masters %}
                                            <option value="{{item.id}}">{{ item.get_full_name }} (рейтинг:  {{ avd|get_item:item.username }})</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    {{ form.master.errors }}
                                </div>
                            </div>

                            <div class="text-center">
                                <div class="form-row">
                                    <div class="form-group row col-md-12">
                                        {{ form.date_of_completion.label_tag }}
                                        {{ form.date_of_completion }}
                                        {{ form.date_of_completion.errors }}
                                    </div>
                                </div>
                            </div>
                            <div class="text-center">
                                <div class="form-row">
                                    <div class="form-group row col-md-12">
                                        {{ form.price.label_tag }}
                                        {{ form.price }}
                                        {{ form.price.errors }}
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 action-row d-flex justify-content-end">
                                <button type="submit" name="next" value="{{ next }}" class="btn">Сохранить</button>
                            </div>
                        </div>

                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<!-- End Profile Section -->
{% endblock %}

orders/templates/order_spec.html
{% extends 'base.html' %}

{% block header %}
<!-- ======= Header ======= -->
<header id="header" class="fixed-top">
    <div class="container-fluid d-flex">
        <div class="logo mr-auto">
            <h1 class="text-light"><a href="/"><span>FixPC.ru</span></a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
        </div>

        <!-- Start nav-menu -->
        <nav class="nav-menu d-none d-lg-block">
            <ul>
                <li><a href="{% url 'base_page' %}#hero">Главная</a></li>
                <li><a href="{% url 'base_page' %}#about">О нас</a></li>
                <li><a href="{% url 'base_page' %}#services">Сервис</a></li>
                <li class="active"><a href="{% url 'orders:select_order' %}">Заказать работу</a></li>
                <li><a href="{% url 'orders:list_specialists' %}">Специалисты</a></li>
                {% if request.user.is_authenticated %}
                <li>
                    <ul>
                        <li class="drop-down">
                            <a href="#">
                                <img class="img-circle img-fluid img-thumbnail" width="25px" height="25px" src="{{ request.user.profile.get_avatar }}">
                                {{ request.user.username }}
                            </a>
                            <ul>
                                <li><a href="{% url 'accounts:profile_info' %}">Профиль</a></li>
                                <li><a href="{% url 'orders:my_order' %}">Мои заказы</a></li>
                                <li><a href="{% url 'accounts:logout'%}?next=/">Выход</a></li>
                            </ul>
                        </li>

                    </ul>
                </li>
                {% else %}
                <li class="get-started">
                    <a href="{% url 'accounts:login'%}">Войти</a>
                </li>
                {% endif %}

            </ul>
        </nav>
        <!-- End nav-menu -->
    </div>
</header>
<!-- End Header -->
{% endblock %}

{% load static %}
{% block content %}
<!-- ======= Profile Section ======= -->
<section class="contact mt-section">
    <div id="auth" class="container">
        <div class="section-title" data-aos="fade-up">
            <!-- ======= Portfolio Section ======= -->
            <section id="portfolio" class="portfolio">
                <div class="container">

                    <div class="section-title" data-aos="fade-up">
                        <h2>Заказ</h2>
                        <p>Выбор категории заказа</p>
                    </div>

                    <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="200">
                        <div class="col-lg-6 col-md-6 portfolio-item filter-app">
                            <div class="portfolio-wrap">
                                <img src="{% static 'img/development.jpg'%}" class="img-fluid" alt="">
                                <div class="portfolio-links">
                                    <a href="{% url 'orders:order_work' category_id=2%}" class="text-center btn-orange"
                                       title="App 1">Заказать</a>
                                </div>
                                <div class="portfolio-info">
                                    <h4>Разработка ПО</h4>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6 col-md-6 portfolio-item filter-web">
                            <div class="portfolio-wrap">
                                <img src="{% static 'img/fix_pc.png' %}" class="img-fluid text-center" alt="">
                                <div class="portfolio-links">
                                    <a href="{% url 'orders:order_work' category_id=1%}" class="text-center btn-orange"
                                       title="Web 3">Заказать</a>

                                </div>
                                <div class="portfolio-info">
                                    <h4>Ремонт ПК</h4>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </section>
            <!-- End Portfolio Section -->
        </div>
    </div>
</section>

<!-- End Profile Section -->
{% endblock %}

orders/templates/specialist.html
{% extends 'base.html' %}

{% block title %}Специалисты{% endblock %}

{% block header %}
<!-- ======= Header ======= -->
<header id="header" class="fixed-top">
    <div class="container-fluid d-flex">
        <div class="logo mr-auto">
            <h1 class="text-light"><a href="/"><span>FixPC.ru</span></a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
        </div>

        <!-- Start nav-menu -->
        <nav class="nav-menu d-none d-lg-block">
            <ul>
                <li><a href="{% url 'base_page' %}#hero">Главная</a></li>
                <li><a href="{% url 'base_page' %}#about">О нас</a></li>
                <li><a href="{% url 'base_page' %}#services">Сервис</a></li>
                <li><a href="{% url 'orders:select_order' %}">Заказать работу</a></li>
                <li class="active"><a href="{% url 'orders:list_specialists' %}">Специалисты</a></li>
                {% if request.user.is_authenticated %}
                <li>
                    <ul>
                        <li class="drop-down">
                            <a href="#">
                                <img class="img-circle img-fluid img-thumbnail" width="25px" height="25px" src="{{ request.user.profile.get_avatar }}">
                                {{ request.user.username }}
                            </a>
                            <ul>
                                <li><a href="{% url 'accounts:profile_info' %}">Профиль</a></li>
                                <li><a href="{% url 'orders:my_order' %}">Мои заказы</a></li>
                                <li><a href="{% url 'accounts:logout'%}?next=/">Выход</a></li>
                            </ul>
                        </li>

                    </ul>
                </li>
                {% else %}
                <li class="get-started">
                    <a href="{% url 'accounts:login'%}">Войти</a>
                </li>
                {% endif %}

            </ul>
        </nav>
        <!-- End nav-menu -->
    </div>
</header>
<!-- End Header -->
{% endblock %}

{% block content %}
<!-- ======= Start List Specialists Section ======= -->
<section class="contact mt-section">
    <div id="auth" class="container">
        <div class="col-12">
        {% for item in list_specialist %}
        <div class="row specialist mb-4">
            <div class="col-12 col-sm-4 col-md-2 text-center mb-4">
                <img class="img-circle img-fluid img-thumbnail" src="{{ item.profile.get_avatar }}">
            </div>
            <div class="col-12 col-sm-8 col-md-10">
                <div class="column ml-2">
                    <h2 class="d-flex align-content-center font-weight-bold">
                        <a href="{% url 'accounts:profile_detail' user_id=item.id %}?page={{ number_page }}">{{ item.get_full_name }}</a>
                    </h2>
                    <div class="row mb-4">
                        <div class="col-12 col-md-6">
                            Телефон: {{ item.profile.phone_number }}
                        </div>
                        <div class="col-12 col-md-6">
                            email: {{ item.email }}
                        </div>
                    </div>
                    <h5 class="font-weight-bold">Обо мне:</h5>
                    <p class="bg-light p-3">{{ item.profile.about_me }}</p>
                    <h5 class="font-weight-bold">Дополнительная информация:</h5>
                    <p class="bg-light p-3">{{ item.profile.additional_info }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="pagination">

            <div class="col-12 d-flex justify-content-center pagination text-center">

                {% if list_specialist.has_previous %}
                <a href="?page={{ list_specialist.previous_page_number }}">←</a>
                {% endif %}

                {% for num in list_specialist.paginator.page_range %}
                {% if num == list_specialist.number %}
                <span class="current"><b>{{ num }}</b></span>
                {% else %}
                <a href="?page={{ num }}"> {{ num }}</a>
                {% endif %}
                {% endfor %}

                {% if list_specialist.has_next %}
                <a href="?page={{ list_specialist.next_page_number }}">→</a>
                {% endif %}

            </div>

        </div>
    </div>
        </div>
</section>
<!-- ======= End List Specialists Section ======= -->
{% endblock %}