accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from .views import RegistrationFormView, CustomPasswordChangeView, profile_view, profile_detail

app_name = "accounts"

urlpatterns = [
    path('', profile_view, name='profile_info'),
    path('detail/<int:user_id>/', profile_detail, name='profile_detail'),

    path('auth/login/',
         auth_views.LoginView.as_view(template_name='registration/login.html', redirect_authenticated_user=True),
         name='login'),
    path('auth/logout/', auth_views.LogoutView.as_view(template_name='registration/login.html', next_page='/'),
         name='logout'),
    path('auth/registration/', RegistrationFormView.as_view(template_name='registration/registration.html',
                                                            success_url=reverse_lazy('accounts:login')),
         name='register'),
    path('auth/password_change/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),
    path('auth/password_change/', CustomPasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done'),
                                                              template_name='registration/password_change.html'),
         name='password_change'),
    path('auth/password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('auth/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_change_done')),
         name='password_reset_confirm'),
    path('auth/password_reset/',
         auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
         name='password_reset'),
]

orders/urls.py
from django.urls import path
from .views import SpecialistsListView, order_view, spec_view, my_orders

app_name = "orders"

urlpatterns = [
    path('list-specialists/', SpecialistsListView.as_view(), name='list_specialists'),
    path('order/<int:category_id>/', order_view, name='order_work'),
    path('select-spec/', spec_view, name='select_order'),
    path('my-orders/', my_orders, name='my_order'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import MainPageView

urlpatterns = [
    path('', MainPageView.as_view(), name='base_page'),
    path('admin/', admin.site.urls),
    path('profile/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, UserManager
from django.db.models import Avg
from django.utils import timezone
from django.core.validators import RegexValidator, MinValueValidator, MaxValueValidator
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _


class AccountManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        # username = self.model.normalize_username(username)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        _default_profile, _ = Profile.objects.get_or_create(surname="Service", name=":", patronymic=":")
        extra_fields.setdefault('profile', _default_profile)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class UsernameValidator(RegexValidator):
    regex = r'^[\w.-]+$'
    message = 'Enter a valid username. This value may contain only letters, ' \
              'numbers, and /./-/_ characters.'
    flags = 0


class BaseAccount(AbstractBaseUser, PermissionsMixin):
    username_validator = UsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator, ],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    email = models.EmailField(_('email address'), unique=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    profile = models.ForeignKey('Profile', on_delete=models.CASCADE)

    objects = AccountManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', ]

    class Meta:
        verbose_name = "аккаунт"
        verbose_name_plural = "аккаунты"
        abstract = True

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        if self.profile:
            full_name = '%s %s %s' % (self.profile.surname.capitalize(),
                                      self.profile.name.capitalize(),
                                      self.profile.patronymic.capitalize())
        else:
            full_name = "-empty-"
        return full_name.strip()

    get_full_name.short_description = 'ФИО'

    def get_short_name(self):
        """Return the short name for the user."""
        if self.profile:
            full_name = '%s %s. %s.' % (self.profile.surname.capitalize(),
                                        self.profile.name[0:1].upper(),
                                        self.profile.patronymic[0:1].upper())
        else:
            full_name = "-empty-"
        return full_name.strip()
    #
    # def email_user(self, subject, message, from_email=None, **kwargs):
    #     """Send an email to this user."""
    #     send_mail(subject, message, from_email, [self.email], **kwargs)


class UserAccount(BaseAccount):
    class Meta(BaseAccount.Meta):
        swappable = 'AUTH_USER_MODEL'


class Profile(models.Model):
    PATH = 'UserAvatar/'
    PATTERN = '^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$'
    POSITIONS = (
        ('master', 'Мастер'),
        ('programmer', 'Программист'),
        ('client', 'Заказчик'),
        ('guest', 'Гость')
    )
    position = models.CharField(max_length=30, verbose_name="Позиция", choices=POSITIONS, default='guest')

    surname = models.CharField(max_length=100, verbose_name="Фамилия", null=False, blank=False)
    name = models.CharField(max_length=100, verbose_name="Имя", null=False, blank=False)
    patronymic = models.CharField(max_length=100, verbose_name="Отчество", null=False, blank=False)
    dob = models.DateField(blank=True, null=True, verbose_name="Дата рождения")
    phone_number = models.CharField(max_length=12, validators=[RegexValidator(PATTERN)], verbose_name="Номер телефона")
    about_me = models.TextField(blank=True, null=True, verbose_name="О себе")
    additional_info = models.TextField(blank=True, null=True, verbose_name="Дополнительная информация")
    photo = models.ImageField(upload_to=PATH, blank=True, null=True, verbose_name='Фото пользователя')
    specialization = models.ForeignKey('Specialization', blank=True, null=True, on_delete=models.CASCADE,
                                       verbose_name='Специализация')
    education = models.ForeignKey('Education', blank=True, null=True, on_delete=models.CASCADE,
                                  verbose_name='Образование')
    work_price = models.ForeignKey('WorkPrice', blank=True, null=True, on_delete=models.CASCADE,
                                   verbose_name='Стоимоть работы')

    def get_avatar(self):
        if not self.photo:
            return '/static/img/user_blank.jpg'
        return self.photo.url

    def avatar_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % self.get_avatar())

    def get_choice_position(self):
        return dict(self.POSITIONS)

    avatar_tag.short_description = 'Avatar'

    def __str__(self):
        return "{surname} {name} {patronymic}".format(surname=self.surname, name=self.name, patronymic=self.patronymic)

    class Meta:
        verbose_name = "профиль"
        verbose_name_plural = "профили"


class Specialization(models.Model):
    name = models.CharField(max_length=200, verbose_name='Специализация')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Специализация"
        verbose_name_plural = "Специализации"


class Education(models.Model):
    name_university = models.ForeignKey('NameEducationalInstitution', on_delete=models.CASCADE,
                                        verbose_name='Университет')
    faculty = models.CharField(max_length=300, verbose_name='Факультет')
    specialization = models.CharField(max_length=300, verbose_name='Специальность')
    graduation_date = models.DateField(verbose_name="Дата окончания")

    def __str__(self):
        return self.name_university.name

    class Meta:
        verbose_name = "Образование"
        verbose_name_plural = "Образования"


class NameEducationalInstitution(models.Model):
    name = models.CharField(max_length=400, verbose_name="Название учебного заведения")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Университет"
        verbose_name_plural = "Университеты"


class WorkPrice(models.Model):
    type_work = models.ForeignKey('TypeWork', on_delete=models.CASCADE, verbose_name="Тип работы")
    price = models.IntegerField(default=0, verbose_name="Цена")

    def __str__(self):
        return "{} {}".format(self.type_work, self.price)

    class Meta:
        verbose_name = "Стоимсоть работы"
        verbose_name_plural = "Стоимость работ"


class TypeWork(models.Model):
    specialization = models.ForeignKey(Specialization, on_delete=models.CASCADE, verbose_name='Специализация')
    name = models.CharField(max_length=150, verbose_name="Тип работы")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Тип работы"
        verbose_name_plural = "Типы работ"


class Comment(models.Model):
    user = models.ForeignKey(UserAccount, on_delete=models.CASCADE, related_name="profile_user", verbose_name='Пользователь')
    user_comment = models.ForeignKey(UserAccount,
                                     on_delete=models.CASCADE,
                                     related_name="comment_user",
                                     verbose_name='Комментирующий Пользователь')
    text_message = models.TextField(verbose_name='Коментарий')
    assessment = models.IntegerField(default=0,
                                     validators=[MinValueValidator(0), MaxValueValidator(5)],
                                     verbose_name='Оценка работы пользователя')
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Дата создания", null=True)

    @staticmethod
    def avd_assessment(user_id):
        comment = Comment.objects.filter(user_id=user_id)
        avg_review = comment.aggregate(Avg('assessment'))['assessment__avg']
        return avg_review

    def __str__(self):
        return 'user_comment: {}, message: {}'.format(self.user, self.text_message)

    class Meta:

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from .models import UserAccount, Profile, Education, NameEducationalInstitution, Comment


class FormRegister(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(), label="Email:")
    username = forms.CharField(max_length=100, label="Имя пользователя:")
    surname = forms.CharField(max_length=100, label="Фамилия:")
    name = forms.CharField(max_length=100, label="Имя:")
    patronymic = forms.CharField(max_length=100, label="Отчество:")
    phone_number = forms.CharField(max_length=12, label="Номер телефона:")
    password1 = forms.PasswordInput()
    password2 = forms.PasswordInput()

    # Стилизация формы
    def __init__(self, *args, **kwargs):
        super(FormRegister, self).__init__(*args, **kwargs)

        for item in self.fields:
            self.fields[item].widget = forms.TextInput(attrs={'class': 'form-control'})

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        # profile =
        if commit:
            prof = Profile.objects.create(
                surname=self.cleaned_data['surname'],
                name=self.cleaned_data['name'],
                patronymic=self.cleaned_data['patronymic'],
                phone_number=self.cleaned_data['phone_number'],
            )
            user.profile = prof
            user.save()
        return user

    class Meta:
        model = UserAccount
        fields = ('username', 'email', 'password1', 'password2')


class FormEdit(ModelForm):
    surname = forms.CharField(max_length=100, label="Фамилия:")
    name = forms.CharField(max_length=100, label="Имя:")
    patronymic = forms.CharField(max_length=100, label="Отчество:")
    phone_number = forms.CharField(required=False, label="Номер телефона:")
    dob = forms.DateField(
        widget=forms.DateInput(format=('%d-%m-%Y')), required=False, label="Дата рождения:")
    about_me = forms.CharField(widget=forms.Textarea(), required=False, label="Обо мне:")
    addition_info = forms.CharField(widget=forms.Textarea(), required=False, label="Дополнмительная информация:")
    avatar_user = forms.FileField(required=False, widget=forms.FileInput, label="Фото:")
    position = forms.ChoiceField(choices=Profile.POSITIONS, label="Позиция")

    university = forms.CharField(required=False, label="Университет:")
    faculty = forms.CharField(max_length=300,  required=False, label="Факультет:")
    specialization = forms.CharField(max_length=300,  required=False, label="Специальность:")
    graduation_date = forms.DateField(
        widget=forms.DateInput(format=('%d-%m-%Y')), required=False, label="Дата окончания:")

    type_work = forms.CharField(required=False, label="Тип работ:")
    price = forms.CharField(required=False, label="Стоимость работ:")

    email = forms.EmailField(max_length=200, label="Email:")
    username = forms.CharField(max_length=100, label="Имя пользователя:")


    # Стилизация формы
    def __init__(self, *args, **kwargs):
        super(FormEdit, self).__init__(*args, **kwargs)

        for item in self.fields:
            self.fields[item].widget = forms.TextInput(attrs={'class': 'form-control'})

    class Meta:
        model = UserAccount
        fields = ('username', 'email',)


class FormComment(ModelForm):
    user = forms.CharField(required=False, label="Пользователь:")
    user_comment = forms.CharField(required=False, label="Комментирующий пользователь:")
    text_message = forms.CharField(widget=forms.Textarea(), required=False, label="Отзыв:")
    assessment = forms.IntegerField(required=False, min_value=0, max_value=5, widget=forms.IntegerField, label="Оценка (0-5):")

    # Стилизация формы
    def __init__(self, *args, **kwargs):
        super(FormComment, self).__init__(*args, **kwargs)

        for item in self.fields:
            self.fields[item].widget = forms.TextInput(attrs={'class': 'form-control'})

    class Meta:
        model = Comment
        fields = ('text_message', 'assessment',)

accounts/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<!-- ======= Profile Section ======= -->
<section class="contact mt-section">
    <div id="auth" class="container">
        <div class="section-title" data-aos="fade-up">
            <h2>Профиль</h2>
            <p>Информация профиля</p>
            {% if flag_save == 1 %}
            <div class="alert alert-success w-100 text-center" role="alert">
                Данные сохранены.
            </div>
            {% elif flag_save == 2%}
            <div class="alert alert-danger w-100" role="alert">
                Ошибка сохранения. Проверьте вводимые данные
            </div>
            {% endif %}
            <form action="{% url 'accounts:profile_info'%}" method="post" role="form" class="row"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-lg-5 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="100">
                    <div class="php-email-form">
                        <h2 class="text-center">Пользователь сайта {{ MEDIA_URL }}{{ user_data.photo.url }}</h2>
                        <div class="panel-body">
                            <div class="" id="author">
                                <div class="col-12 form-row">
                                    <div class="col-12 text-center">
                                        <img class="img-circle img-fluid img-thumbnail"
                                             src="{{ user_data.profile.get_avatar }}">
                                    </div>
                                    <div class="form-group row col-12">
                                        {{ form.avatar_user.label_tag }}
                                        <input type="file" class="col-12" name="avatar_user" id="avatar_user"
                                               value=""/>
                                        {{ form.avatar_user.errors }}
                                    </div>
                                </div>

                                <div class="mt-2 form-group">
                                    <label for="username">Имя пользователя на сайте:</label>
                                    <input type="text" class="form-control" name="username" id="username"
                                           value="{{ user_data.username }}"/>
                                    {{ form.username.errors }}
                                </div>
                                <div class="form-group">
                                    <label for="about_me">Обо мне</label>
                                    <textarea class="form-control" name="about_me" rows="10" data-rule="required"
                                              id="about_me">{{ user_data.profile.about_me }}</textarea>
                                    {{ form.profile.about_me.errors }}
                                </div>
                                <div class="form-group">
                                    <label for="addition_info">Дополнительная информация:</label>
                                    <textarea class="form-control" name="addition_info" rows="10" data-rule="required"
                                              id="addition_info">{{ user_data.profile.addition_info }}</textarea>
                                    {{ form.profile.addition_info.errors }}
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="col-lg-7 mt-5 mt-lg-0 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="200">
                    <div class="php-email-form">
                        <div class="form-row">
                            <div class="form-group row col-md-12">
                                {{ form.position.label_tag }}
                                <select name="position" class="form-control selectpicker" id="position">
                                    {% for key, val in user_data.profile.get_choice_position.items %}
                                    {% if key == user_data.profile.position %}
                                    <option selected value="{{ key }}">{{ val }}</option>
                                    {% else %}
                                    <option value="{{ key }}">{{ val }}</option>
                                    {% endif %}
                                    {% endfor %}
                                </select>
                                {{ form.position.errors }}
                            </div>
                            <div class="form-group row col-md-12">
                                <label for="surname">Фамилия:</label>
                                <input type="text" class="form-control" name="surname" id="surname" data-rule="email"
                                       value="{{ user_data.profile.surname }}"/>
                                {{ form.surname.errors }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group row col-md-12">
                                <label for="name">Имя:</label>
                                <input type="text" class="form-control" name="name" id="name"
                                       value="{{ user_data.profile.name }}"/>
                                {{ form.name.errors }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group row col-md-12">
                                <label for="patronymic">Отчество:</label>
                                <input type="text" class="form-control" name="patronymic" id="patronymic"
                                       data-rule="email"
                                       value="{{ user_data.profile.patronymic }}"/>
                                {{ form.patronymic.errors }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group row col-md-12">
                                <label for="dob">Дата рождения:</label>
                                <input type="text" class="form-control" name="dob" id="dob"
                                       value="{{ user_data.profile.dob|date:'d.m.Y' }}"/>
                                {{ form.dob.errors }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group row col-md-12">
                                <label for="email">Email:</label>
                                <input type="email" class="form-control" name="email" id="email" required
                                       data-rule="email"
                                       value="{{ user_data.email }}"/>
                                {{ form.email.errors }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group row col-md-12">
                                <label for="phone_number">Телефон:</label>
                                <input type="text" class="form-control" name="phone_number" id="phone_number"
                                       data-rule="email"
                                       value="{{ user_data.profile.phone_number }}"/>
                                {{ form.phone.errors }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group row col-md-12">
                                {{ form.university.label_tag }}
                                <div class="w-100">
                                    <select name="university" class="form-control selectpicker" id="id_university">
                                        <option value="">Выберите университет</option>
                                        {% for item in university %}
                                        {% if item == user_data.profile.education.name_university %}
                                        <option selected value="{{ item.id }}">{{item}}</option>
                                        {%else%}
                                        {% endif %}
                                        <option value="{{item.id}}">{{ item }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                {{ form.university.errors }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group row col-md-12">
                                {{ form.faculty.label_tag }}
                                <input type="text" class="form-control" name="faculty" id="faculty"
                                       value="{{ user_data.profile.education.faculty }}"/>
                                {{ form.faculty.errors }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group row col-md-12">
                                {{ form.specialization.label_tag }}
                                <input type="text" class="form-control" name="specialization" id="specialization"
                                       value="{{ user_data.profile.education.specialization }}"/>
                                {{ form.specialization.errors }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group row col-md-12">
                                {{ form.graduation_date.label_tag }}
                                <input type="text" class="form-control" name="graduation_date" id="graduation_date"
                                       value="{{ user_data.profile.education.graduation_date|date:'d.m.Y' }}"/>
                                {{ form.graduation_date.errors }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group row col-md-12">
                                {{ form.type_work.label_tag }}
                                <div class="w-100">
                                    <select name="type_work" class="form-control selectpicker" id="id_type_work">
                                        <option value="">Выберите тип работы</option>
                                        {% for item in type_work %}
                                        {% if item == user_data.profile.work_price.type_work %}
                                        <option selected value="{{item.id}}">{{ item.name }}</option>
                                        {% else %}
                                        <option value="{{item.id}}">{{ item.name }}</option>
                                        {% endif %}
                                        {% endfor %}
                                    </select>
                                </div>
                                {{ form.type_work.errors }}
                            </div>
                        </div>


                        <div class="form-row">
                            <div class="form-group row col-md-12">
                                {{ form.price.label_tag }}
                                <input type="text" class="form-control" name="price" id="id_price"
                                       value="{{ user_data.profile.work_price.price }}"/>
                                {{ form.price.errors }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group row col-md-12">
                                <a class="btn-link" href="{% url 'accounts:password_change' %}">Изменить пароль</a>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group row col-md-12">
                                <label for="phone_number">Зарегистрирован:</label>
                                <input type="text" class="form-control" readonly="readonly" name="date_joined"
                                       id="date_joined"
                                       value="{{ user_data.date_joined }}"/>
                            </div>
                        </div>
                        <div class="action-row d-flex justify-content-end">
                            <button type="submit" name="next" value="{{ next }}" class="btn">Сохранить</button>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</section>

<!-- End Profile Section -->
{% endblock %}